Models/DepartmentViewModel.cs
namespace DepartmentsWEB.Models
{
    public class DepartmentViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public List<PersonViewModel> People { get; set; }
    }
}

Models/DepartmentVisualViewModel.cs
namespace DepartmentsWEB.Models
{
    public class DepartmentVisualViewModel
    {
        public DepartmentViewModel Department { get; set; }
        public List<DepartmentViewModel> Departments { get; set; }
    }
}

Models/NewPersonViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace DepartmentsWEB.Models
{
    public class NewPersonViewModel
    {
        public List<DepartmentViewModel> Departments { get; set; }

        [Required(ErrorMessage = "Укажите фамилию! Это обязательное поле.")]
        public string LastName { get; set; } = string.Empty;

        [Required(ErrorMessage = "Укажите имя! Это обязательное поле.")]
        public string FirstName { get; set; } = string.Empty;

        public int DepartmentId { get; set; } = 0;

        public NewPersonViewModel()
        {
            Departments = new List<DepartmentViewModel>();
        }
    }
}

Models/PersonViewModel.cs
namespace DepartmentsWEB.Models
{
    public class PersonViewModel
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public int DepartmentId { get; set; }
    }
}

Controllers/HomeController.cs
using AutoMapper;
using DepartmentsWEB.db.Interfaces;
using DepartmentsWEB.Helpers;
using DepartmentsWEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace DepartmentsWEB.Controllers
{
    public class HomeController : Controller
    {
        private IDepartmentsRepository departmentsRepository;
        private IPersonsRepository personsRepository;
        private readonly IMapper mapper;

        public HomeController(IDepartmentsRepository departmentsRepository, IPersonsRepository personsRepository, IMapper mapper)
        {
            this.departmentsRepository = departmentsRepository;
            this.personsRepository = personsRepository;
            this.mapper = mapper;
        }

        public IActionResult Index(int id = 1)
        {
            var departmentVM = new CreateVisual(departmentsRepository, mapper).ToCreateVisual(id);
            return View(departmentVM);
        }

        public IActionResult ChangeDepartment(int personId, int newDepartmentId)
        {
            personsRepository.ChangeDepartment(personId, newDepartmentId);
            return RedirectToAction("Index", "Home", new { id = newDepartmentId });
        }

        public IActionResult AddPerson()
        {
            NewPersonViewModel newPerson = new NewPersonViewModel();
            newPerson.Departments = new CreateVisual(departmentsRepository, mapper).ToDepartmentsVM();
            return View(newPerson);
        }

        [HttpPost]
        public IActionResult AddPerson(NewPersonViewModel newPerson)
        {
            if (ModelState.IsValid)
            {
                var person = newPerson.ToPerson();
                personsRepository.AddPerson(person);
                return RedirectToAction("Index", "Home", new { id = person.DepartmentId });
            }
            newPerson.Departments = new CreateVisual(departmentsRepository, mapper).ToDepartmentsVM();
            return View(newPerson);
        }
    }
}

Views/Shared/Components/Departments/DepartmentsViewComponent.cs
using AutoMapper;
using DepartmentsWEB.db.Interfaces;
using DepartmentsWEB.Models;
using Microsoft.AspNetCore.Mvc;

namespace DepartmentsWEB.Views.Shared.Components.Departments
{
    public class DepartmentsViewComponent : ViewComponent
    {
        private readonly IDepartmentsRepository departmentsRepository;
        private readonly IMapper mapper;
        public DepartmentsViewComponent(IDepartmentsRepository departmentsRepository, IMapper mapper)
        {
            this.departmentsRepository = departmentsRepository;
            this.mapper = mapper;
        }

        public IViewComponentResult Invoke()
        {
            var departmentsDb = departmentsRepository.GetAll();
            var departmentsVM = mapper.Map<List<DepartmentViewModel>>(departmentsDb);

            return View("Departments", departmentsVM);
        }
    }
}

Views/Home/AddPerson.cshtml
@model NewPersonViewModel

<div class="validation validation-message" asp-validation-summary="ModelOnly"></div>

<div class="addperson">
    <h5>Добавление нового сотрудника</h5>
    <form method="post">

        <label asp-for="LastName">Фамилия</label>
        <input asp-for="LastName" type="text" class="form-control">
        <span asp-validation-for="LastName" style="color:brown"></span>
        <br />

        <label asp-for="FirstName">Имя</label>
        <input asp-for="FirstName" type="text" class="form-control">
        <span asp-validation-for="FirstName" style="color:brown"></span>`
        <br>

        <label for="DepartmentId">Выберите подразделение</label>
        <select name="DepartmentId">
            @foreach (var department in Model.Departments)
            {
                <option value="@department.Id">@department.Name</option>
            }
        </select>

        <button class="btn btn-secondary addpersonbutton" type="submit" asp-area="" asp-controller="home" asp-action="addperson">Добавить</button>
    </form>
</div>

Views/Home/Index.cshtml
@model DepartmentVisualViewModel

<body>
    @await Component.InvokeAsync("Departments")
    <div class="persons">
        <h2>@Model.Department.Name</h2>
        <table class="persontable">
            <thead>
                <tr>
                    <th>Фамилия</th>
                    <th>Имя</th>
                    <th>Подразделение</th>
                    <th>Сменить</th>
                </tr>
            </thead>
            @foreach (var person in Model.Department.People)
            {
                <tbody>
                    <tr>
                        <td>@person.LastName</td>
                        <td>@person.FirstName</td>
                        <td>@Model.Department.Name</td>
                        <td>
                            <div class="dropdown">
                                <a class="btn btn-outline-secondary dropdown-toggle" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                                    Сменить подразделение
                                    <span class="caret"></span>
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                                    @foreach (var department in Model.Departments)
                                    {
                                        @if (department.Id == Model.Department.Id)
                                        {
                                            <li><a class="btn btn-secondary" asp-area="" asp-controller="home" asp-action="changedepartment" asp-route-personId="@person.Id" asp-route-newDepartmentId="@department.Id">@department.Name</a></li>
                                        }
                                        else
                                        {
                                            <li><a class="btn btn-outline-secondary" asp-area="" asp-controller="home" asp-action="changedepartment" asp-route-personId="@person.Id" asp-route-newDepartmentId="@department.Id">@department.Name</a></li>
                                        }
                                    }
                                </ul>
                            </div>
                        </td>
                    </tr>
                </tbody>
            }
        </table>
        <div class="addpersonbutton">
            <a class="btn btn-secondary" asp-area="" asp-controller="home" asp-action="addperson" asp-route-id="@Model.Department.Id">Добавить сотрудника</a>
        </div>
    </div>
</body>

Views/Shared/Components/Departments/Departments.cshtml
@model List<DepartmentViewModel>

<div class="leftblock">
    <div class="btn-group-vertical btn-group-lg" role="group">
        @foreach (var department in Model)
        {
            <a type="button" class="btn" asp-area="" asp-controller="home" asp-action="index" asp-route-id="@department.Id">@department.Name</a>
        }
    </div>
</div>

Views/Shared/Footer.cshtml
<footer>
</footer>

Views/Shared/Header.cshtml
<header>
    <nav class="navbar">
            <center><h2>Подразделения и сотрудники</h2></center>
    </nav>
</header>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DepartmentsWEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DepartmentsWEB.styles.css" asp-append-version="true" />
</head>
<body>
    @await Html.PartialAsync("Header")
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @await Html.PartialAsync("Footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>